# Generated by Django 4.2.2 on 2023-07-01 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('hp', models.IntegerField(default=0)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='main_app.manufacture')),
            ],
        ),
    ]
