# Generated by Django 4.2.2 on 2023-07-01 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='hp',
            new_name='length',
        ),
    ]
